apiVersion: apps/v1
kind: Deployment
metadata:
  name: blue-deployment
  namespace: blue-green
spec:
  replicas: 3
  selector:
    matchLabels:
      app: flask-app
      version: blue
  template:
    metadata:
      labels:
        app: flask-app
        version: blue
    spec:
      containers:
      - name: flask-app
        image: crinklefriez/flask-app:blue
        imagePullPolicy: Always
        ports:
        - containerPort: 5000
        env:
        - name: APP_VERSION
          value: "1.0"
        - name: APP_COLOR
          value: "blue"
