apiVersion: v1
kind: Service
metadata:
  name: green-service
  namespace: blue-green
spec:
  type: ClusterIP
  selector:
    app: flask-app
    version: green
  ports:
  - port: 80
    targetPort: 5000
    protocol: TCP
