apiVersion: apps/v1
kind: Deployment
metadata:
  name: green-deployment
  namespace: blue-green
spec:
  replicas: 3
  selector:
    matchLabels:
      app: flask-app
      version: green
  template:
    metadata:
      labels:
        app: flask-app
        version: green
    spec:
      containers:
      - name: flask-app
        image: crinklefriez/flask-app:green
        imagePullPolicy: Always
        ports:
        - containerPort: 5000
        env:
        - name: APP_VERSION
          value: "2.0"
        - name: APP_COLOR
          value: "green"
