apiVersion: v1
kind: Service
metadata:
  name: flask-app-service
  namespace: blue-green
spec:
  type: NodePort
  selector:
    app: flask-app
    version: blue
  ports:
  - port: 80
    targetPort: 5000
    nodePort: 30081
    protocol: TCP
